include:
  - remnux.tools.js-patched
  - remnux.tools.networkminer
  - remnux.tools.jd-gui
  - remnux.tools.cyberchef
  - remnux.tools.cfr
  - remnux.tools.cutter
  - remnux.tools.fakedns
  - remnux.tools.shellcode2exe-bat
  - remnux.tools.bytehist
  - remnux.tools.trid
  - remnux.tools.manalyze
  - remnux.tools.apktool
  - remnux.tools.polarproxy
  - remnux.tools.ssview
  - remnux.tools.yara-rules
  - remnux.tools.yara-forge
  - remnux.tools.jadx
  - remnux.tools.detect-it-easy
  - remnux.tools.capa
  - remnux.tools.docker-compose
  - remnux.tools.ghidrassist-mcp
  - remnux.tools.goresym
  - remnux.tools.redress
  - remnux.tools.yara-x

remnux-tools:
  test.nop:
    - require:
      - sls: remnux.tools.js-patched
      - sls: remnux.tools.networkminer
      - sls: remnux.tools.jd-gui
      - sls: remnux.tools.cyberchef
      - sls: remnux.tools.cfr
      - sls: remnux.tools.cutter
      - sls: remnux.tools.fakedns
      - sls: remnux.tools.shellcode2exe-bat
      - sls: remnux.tools.bytehist
      - sls: remnux.tools.trid
      - sls: remnux.tools.manalyze
      - sls: remnux.tools.apktool
      - sls: remnux.tools.polarproxy
      - sls: remnux.tools.ssview
      - sls: remnux.tools.yara-rules
      - sls: remnux.tools.yara-forge
      - sls: remnux.tools.jadx
      - sls: remnux.tools.detect-it-easy
      - sls: remnux.tools.capa
      - sls: remnux.tools.docker-compose
      - sls: remnux.tools.ghidrassist-mcp
      - sls: remnux.tools.goresym
      - sls: remnux.tools.redress
      - sls: remnux.tools.yara-x
